### PR TITLE
Improve German translations

### PR DESCRIPTION
**Pull request by MoritzLost**
The German translations had a bunch of spelling and stylistic errors, this PR fixes some of them.

- Use real umlauts (ä ö ü) instead of replacements (ae oe ue). The latter form was used for a bunch of translations, but that isn't really done in German. You only see these forms in very old systems that only support ASCII …
- Use common translation patterns from the core (e.g. use `Control Panel` verbatim instead of an awkward translation).
- Clean up formatting and whitespace (use spaces consistently to match the core files).
- Add a missing translation (`'Add existing fields' => 'Vorhandene Felder hinzufügen'`)

The PR targets the craft-4 branch, might want to merge that into craft-5 as well.

---

A general question, is there any plan for how those German translations will be maintained?

The German translations are a great contribution, however they put us into a bit of an awkward spot. For most of our clients, having one plugin interface in English is fine (Germans can generally understand English well enough). But having translations that are awkward and in some places downright broken is an issue. But since they're in formie's core files, there isn't really an option _not_ to use them if clients use the CMS in German. So we have to clean up if we want a usable interface.

I'm worried that the translations will get out of sync and a lot of missing translations will appear if there isn't anyone dedicated to maintaining those translations. 

There's already a bit of chaos in the `de.php` file. A couple of translations that weren't in the source file were added at the end, already hard to find the right place to add a missing translation in there.

### CODE REVIEW

**Comment by engram-design** [comment]
Thanks!

The original translations were from https://github.com/verbb/formie/pull/1760 and we're still considering our options for translations to multiple languages across all our plugins. But you raise an interesting point, that something like this would be best omitted rather than appear broken or incomplete. Indeed, it's not a great look for us if things appear misspelled or grammatically incorrect.

We'll give this some consideration into something more maintainable!

**Comment by engram-design** [comment]
As an aside, I’ve been experimenting with Deepl to automate translations. I’m well aware that it’s not magic and going to be 100% correct, but keen to get your thoughts 

https://gist.github.com/engram-design/00b9a12cb12d0d39d72809f1e7776d22

I’m pretty sure we’ll always need a native speaker to fix things up, but just experimenting with options.

**Comment by janhenckens** [comment]
Hey @engram-design, I saw the German translations update in the changelog and I was wondering if you'd be open to a PR to add Dutch translations?

**Comment by engram-design** [comment]
@janhenckens Of course, PR's are always welcome. Although I can't say that I'll be able to keep them updated (as with German) with my lack of Dutch language skills.

**Pull request merged**
