### PR TITLE
Add more German translations, clean up

### PR DESCRIPTION
**Pull request by MoritzLost**
- Adds German translations to the new strings added in response to #1836
- Improve some German translations
- Add some missing translations
- Remove some duplicates from English and German translation files
- Remove some unused translations
- Some whitespace and formatting adjustments to keep translation files in sync

There are still some translations at the end of the `de/formie.php` file that aren't present in `en/formie.php`, but _are_ used in the plugin. Maybe those could be added to `en/formie.php` as well and sorted properly in both files – I still don't get how those translations are ordered 🙃. Having both files in sync makes it much easier to contribute individual translations for new strings that are added to the core. I tried to clean up as much as possible.

@engram-design Follow up to #1836 and #1835 … yeah, a plan for keeping German translations up to date would be good. I can't really justify the time to do this every time 😇  Of course, we don't expect every plugin developer to have the same language support as the core. But as you said, having outdated/incorrect translations is sometimes worse than having no translations.

### CODE REVIEW

**Comment by engram-design** [comment]
Really appreciate your work on this, I would’ve hoped the original translation was workable.

Translations are a bit of a mess at the moment, and actively working on improving that, as well as automating the English ones so that stuff doesn’t get missed.

As for translations in general, imagine we didn’t have your excellent translations in place, would you rather see an automated, 90% complete German translation of things (an example https://gist.github.com/engram-design/00b9a12cb12d0d39d72809f1e7776d22) or would you rather see English instead?

Just tossing up our options here. [CrowdIn](https://crowdin.com/) is probably our best bet for accurate translations.

**Comment by MoritzLost** [comment]
@engram-design 

> As for translations in general, imagine we didn’t have your excellent translations in place, would you rather see an automated, 90% complete German translation of things (an example https://gist.github.com/engram-design/00b9a12cb12d0d39d72809f1e7776d22) or would you rather see English instead?

Not sure I can speak for all Germans here ^^

Personally, I don't care about translations, my account is always set to English. German is awkward for interfaces – too many long words and compound words, and technical terms that have no good translation.

Many of my clients will be fine using an English interface, but definitely not all.

90% German translations would be preferable over no German translations. However, **accuracy** of the translations is more important than **completeness**. A German interface with a couple of English strings in it is fine. But if the translations are inaccurate, misspelled or incorrect, that's a bigger problem. So having good translations is more important than having translations for everything, and bad translations are worse than no translations.

> As an aside, I’ve been experimenting with Deepl to automate translations. 

Those translations look pretty good!

DeepL is definitely the best option. Better than Google translate in my opinion. I also tried cleaning up the translations with ChatGPT 4, but it just told me to do it myself 🤷 

Fully automatic will never work well:

- Some translations require the context of how they're used. For example `Save Button Style` – is that the label for an option to configure the style of a save button, or is it the label for the submit button in a form where I can configure a button style? No way to tell without looking at the context where the translation is used. All automatic translation tools can only guess.
- Technical terms without a clear translations. A bunch of technical terms have no real translation and are best kept as is when translating to German. But those tools tend to find awkward phrases or reword the string entirely, often to the point where it's illegible. For example, `Snapshot` has no real counterpart in German, but I've seen that translated as something like `Shadow clone` …
- Translation patterns and conventions. The core translates some words consistently in a specific way. For example, `Control Panel` ist always kept as-is. I experimented with giving the core `translations/app.php` to ChatGPT to use as context for how to translate certain phrases, but I don't think it's there yet.

Automatic translations with oversight by a human speaker is probably the way to go.

> Just tossing up our options here. [CrowdIn](https://crowdin.com/) is probably our best bet for accurate translations.

I've contributed a couple of times in the Craft CMS CrowdIn. Kind of hard to navigate, but workable ^^

**Comment by MoritzLost** [comment]
@engram-design Can we get another release with this PR soon? Really want to finish the Formie integration in my current project :)

**Comment by engram-design** [comment]
Thanks for the feedback, certainly appreciate that! 

I’ve added a little module here https://github.com/verbb/plugin-translator which at the very least automates and orders English translations, so you can expect a proper order to strings. Jury is still out on using Deepl’s translations though.

Should have a release over the weekend. I’ll ping you with one final update shortly.

**Comment by MoritzLost** [comment]
@engram-design That plugin translator looks like a really good starting point!

**Comment by engram-design** [comment]
I've just finalised the [English](https://github.com/verbb/formie/blob/craft-4/src/translations/en/formie.php) translations, which are now automated for future use. They're alphabetically ordered to make it easier to deal with (apart from the special email messages).

As such, I've incorporated this into the [German](https://github.com/verbb/formie/blob/craft-4/src/translations/de/formie.php) translations which follow the same order. The process of this was to start with the English file and pull in any matching values that you and others had made. This means that if any text has been missed, it'll still be in the German translation file it'll just be in English.

Hope that helps, and thanks for the continued support with this!

**Comment by MoritzLost** [comment]
@engram-design This looks great, thanks! Much easier to submit new translations this way. I see there are still a bunch of translations missing in German, if I have the time I'll submit some more translations as I come across them.

**Pull request merged**
